import type {
  InteractiveScenarioBeat,
  InteractiveScenarioDef,
  InteractiveScenarioGoal,
} from './interactive-scenario.types';
import adventureA2ScenariosJson from './adventure-a2-scenarios.json';

const ROOFTOP_BG = 'assets/images/learn/scenario/final_interview_rooftop_bg.jpg';

/** Stimulus cards in Firebase Storage (upload: scripts/upload-describe-it-images.ts final_interview_john). */
const cardPath = (file: string) => `describe-it/v7_finale_n01/${file}.webp`;

/**
 * Path Finale — ungraded "Are you ready?" intro + 16 scored questions covering
 * every A1 Foundations chapter (V7 ch.1–16). One question per turn. Visual stimuli are Firebase picture cards
 * (beat.imagePath) shown beside John — no emoji cards on those beats.
 */
const GOALS: InteractiveScenarioGoal[] = [
  {
    id: 'name',
    labelTh: 'บอกชื่อ',
    labelEn: 'Say your name',
    meaningRubric: "States a name — My name is X / I am X / I'm X. Real or made-up names are fine.",
    acceptExamples: ['My name is Maya', "I'm Max", 'I am Ana'],
    // Matched by the runtime name extractor.
    measuresChapters: [1],
    hints: { intentTh: 'บอกชื่อของคุณ', starterEn: 'My name is…', modelEn: 'My name is Maya.' },
  },
  {
    id: 'from_live',
    labelTh: 'บอกว่ามาจากไหน',
    labelEn: 'Say where you are from',
    meaningRubric: "Says origin or home — I'm from X / I live in X. Real or made-up is fine.",
    acceptExamples: ["I'm from Thailand", 'I am from Bangkok', 'I live in Chiang Mai'],
    matchPatterns: ['\\bfrom\\b', '\\blive (in|at)\\b'],
    measuresChapters: [1],
    hints: { intentTh: "บอกว่ามาจากไหน ด้วย I'm from…", starterEn: "I'm from…", modelEn: "I'm from Thailand." },
  },
  {
    id: 'age',
    labelTh: 'บอกอายุ',
    labelEn: 'Say your age',
    meaningRubric: 'Gives an age with a number — I am twenty / I am 20 years old. Made-up is fine.',
    acceptExamples: ['I am twenty', "I'm 18", 'I am twenty years old', 'Twenty'],
    matchPatterns: [
      '\\b\\d{1,2}\\b',
      '\\b(ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety)\\b',
      '\\byears old\\b',
    ],
    measuresChapters: [3, 8],
    hints: { intentTh: 'บอกอายุด้วย I am + ตัวเลข', starterEn: 'I am…', modelEn: 'I am twenty years old.' },
  },
  {
    id: 'family',
    labelTh: 'แนะนำคนในครอบครัว',
    labelEn: 'Talk about one family member',
    meaningRubric: 'Introduces a family member — This is my mother / My brother is a student / He is my father.',
    acceptExamples: ['This is my mother', 'My brother is a student', 'This is my sister. She is a doctor.'],
    matchPatterns: ['\\b(mother|father|mom|mum|dad|sister|brother|aunt|uncle|cousin|grandmother|grandfather|grandma|grandpa|son|daughter|wife|husband)\\b'],
    measuresChapters: [4],
    hints: { intentTh: 'ใช้ This is my… แล้วบอกว่าเขาเป็นใคร', starterEn: 'This is my…', modelEn: 'This is my brother. He is a student.' },
  },
  {
    id: 'this_that',
    labelTh: 'บอกว่าไม่ใช่ และชี้กระเป๋าที่ถูก',
    labelEn: 'Say no and point to the right bag',
    meaningRubric: "The bag in the picture is red; John's bag is blue. Says it is not his / it is not John's bag.",
    acceptExamples: ['No, it is not. That is your bag.', 'No', "No, that's your bag", 'That blue bag'],
    matchPatterns: ["\\b(no|not|isn'?t)\\b", "\\bthat( is|'s)? (your|the blue)\\b", '\\bblue\\b'],
    measuresChapters: [6],
    hints: { intentTh: 'บอกว่าไม่ใช่ แล้วชี้ว่า "ใบนั้น" คือกระเป๋าของครู', starterEn: 'No, it is not. That is…', modelEn: 'No, it is not. That is your bag.' },
  },
  {
    id: 'have',
    labelTh: 'บอกของที่มีในกระเป๋า',
    labelEn: 'Say what you have',
    meaningRubric: 'Uses I have + objects (a/an, plural -s welcome).',
    acceptExamples: ['I have a phone', 'I have a key and two books', 'A phone and a pen'],
    matchPatterns: ['\\bhave\\b', '\\b(phone|key|keys|book|books|pen|pens|wallet|bottle)\\b'],
    measuresChapters: [7],
    hints: { intentTh: 'ใช้ I have… บอกของในกระเป๋า', starterEn: 'I have…', modelEn: 'I have a book.' },
  },
  {
    id: 'plural',
    labelTh: 'บอกจำนวนแอปเปิล (พหูพจน์)',
    labelEn: 'Say how many apples (plural)',
    meaningRubric: 'Three apples are on the table. Says the number with a plural noun — Three apples / There are three apples. "Three apple" (no -s) = close.',
    acceptExamples: ['Three apples', 'There are three apples', '3 apples'],
    matchPatterns: ['\\b(three|3) apples\\b', '\\bthere are (three|3)\\b'],
    measuresChapters: [5],
    hints: { intentTh: 'บอกจำนวน + คำนามเติม s', starterEn: 'Three…', modelEn: 'There are three apples.' },
  },
  {
    id: 'wake_time',
    labelTh: 'บอกเวลาตื่นนอน',
    labelEn: 'Say what time you wake up',
    meaningRubric: 'Gives a clock time for waking up — I wake up at seven.',
    acceptExamples: ['I wake up at seven', 'At six', 'Six thirty'],
    matchPatterns: [
      "\\b(\\d{1,2}|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve)( o'?clock| thirty| am| a m)?\\b",
    ],
    measuresChapters: [9],
    hints: { intentTh: 'บอกเวลาที่ตื่นนอน', starterEn: 'I wake up at…', modelEn: 'I wake up at seven.' },
  },
  {
    id: 'her_day',
    labelTh: 'เล่ากิจวัตรของ May',
    labelEn: "Tell May's day (she + verb-s)",
    meaningRubric: "Describes May's routine in 3rd person: She wakes up at seven / She works at eight. Missing -s = close.",
    acceptExamples: ['She wakes up at seven', 'She works at eight', 'She wakes up at seven. She works at eight.'],
    matchPatterns: ['\\b(wakes|works|gets up|goes|eats|starts)\\b'],
    measuresChapters: [12],
    hints: { intentTh: 'ใช้ She + กริยาเติม s', starterEn: 'She wakes up at…', modelEn: 'She wakes up at seven. She works at eight.' },
  },
  {
    id: 'happening_now',
    labelTh: 'บอกว่า Max กำลังทำอะไร',
    labelEn: 'Say what Max is doing now',
    meaningRubric: 'Uses is + -ing for an action happening now — He is eating.',
    acceptExamples: ['He is eating', "He's eating", 'Eating'],
    matchPatterns: ['\\beating\\b', "\\b(is|he'?s|hes)\\s+\\w+ing\\b"],
    measuresChapters: [13],
    hints: { intentTh: 'ใช้ He is … -ing', starterEn: 'He is…', modelEn: 'He is eating.' },
  },
  {
    id: 'like',
    labelTh: 'บอกว่าชอบอะไร',
    labelEn: 'Say what you like',
    meaningRubric: "Says a preference between coffee and tea — I like tea / I don't like coffee.",
    acceptExamples: ['I like tea', "I don't like coffee", 'I like coffee'],
    matchPatterns: ['\\b(like|love|likes)\\b'],
    measuresChapters: [10],
    hints: { intentTh: "ใช้ I like… / I don't like…", starterEn: 'I like…', modelEn: "I like tea. I don't like coffee." },
  },
  {
    id: 'can',
    labelTh: 'บอกสิ่งที่ทำได้',
    labelEn: 'Say what you can do',
    meaningRubric: "Uses can / can't + action — Yes, I can. I can swim.",
    acceptExamples: ['I can swim', 'Yes, I can', "No, I can't", 'I can cook'],
    matchPatterns: ["\\b(can|can'?t|cannot)\\b"],
    measuresChapters: [11],
    hints: { intentTh: "ใช้ I can… / I can't…", starterEn: 'I can…', modelEn: 'Yes, I can. I can swim and cook.' },
  },
  {
    id: 'ask_back',
    labelTh: 'ถามครูจอห์นหนึ่งคำถาม',
    labelEn: 'Ask Teacher John a question',
    meaningRubric: 'Forms any simple A1 question to John (Can you…? / Do you…? / What/Who/Where/When…? / How are you?).',
    acceptExamples: ['Can you cook?', 'Do you like coffee?', 'Where are you from?', 'How are you?'],
    // Matched by the question detector in the runtime (learnerMayAsk beat).
    measuresChapters: [14],
    hints: { intentTh: 'ถามครูกลับหนึ่งคำถาม', starterEn: 'Can you…?', modelEn: 'Can you cook?' },
  },
  {
    id: 'ask_price',
    labelTh: 'ถามราคาเสื้อสีแดง',
    labelEn: 'Ask the price of the red shirt',
    meaningRubric: 'Asks the price with How much…? (How much is the red shirt? / How much is it?).',
    acceptExamples: ['How much is the red shirt?', 'How much is it?', 'How much?'],
    matchPatterns: ['\\bhow much\\b', '\\bprice\\b'],
    measuresChapters: [15],
    hints: { intentTh: 'ถามราคาด้วย How much…?', starterEn: 'How much is…?', modelEn: 'How much is the red shirt?' },
  },
  {
    id: 'directions',
    labelTh: 'บอกทางไปที่ประตู',
    labelEn: 'Give directions to the door',
    meaningRubric: 'Route on the map: go straight, then turn left. Accept either step or both.',
    acceptExamples: ['Go straight and turn left', 'Go straight', 'Turn left'],
    matchPatterns: ['\\b(straight|left)\\b'],
    measuresChapters: [16],
    hints: { intentTh: 'บอกทางด้วย Go straight / Turn left', starterEn: 'Go straight and…', modelEn: 'Go straight and turn left.' },
  },
  {
    id: 'goodbye',
    labelTh: 'ขอบคุณและบอกลา',
    labelEn: 'Say thank you and goodbye',
    meaningRubric: 'Any polite close — Thank you / Goodbye / See you.',
    acceptExamples: ['Thank you! Goodbye!', 'See you', 'Bye', 'See you tomorrow'],
    matchPatterns: ['\\b(bye|goodbye|see you|thank you|thanks)\\b'],
    measuresChapters: [2],
    hints: { intentTh: 'ขอบคุณ แล้วบอกลา', starterEn: 'Thank you…', modelEn: 'Thank you! Goodbye! See you!' },
  },
];

const beat = (
  b: Omit<InteractiveScenarioBeat, 'sceneId' | 'visualLayout'> &
    Partial<Pick<InteractiveScenarioBeat, 'sceneId' | 'visualLayout'>>,
): InteractiveScenarioBeat => ({
  sceneId: 'rooftop',
  visualLayout: 'beside_teacher',
  ...b,
});

const BEATS: InteractiveScenarioBeat[] = [
  beat({
    id: 't01_ready',
    // Intro only — any reply continues, not scored.
    ungraded: true,
    focusGoalIds: [],
    npcBriefEn: 'Final boss intro on the school rooftop. Ask if the learner is ready.',
    promptEn: 'Finally… you made it to the top. Great job! One last test before you leave. Are you ready?',
    promptTh: 'ในที่สุดคุณก็มาถึงจุดนี้ได้ เยี่ยมมาก! บททดสอบสุดท้ายก่อนออกจากโรงเรียน… พร้อมไหมครับ?',
    praiseEn: ["Ha! I like that. Let's begin."],
  }),
  beat({
    id: 't02_name',
    focusGoalIds: ['name'],
    npcBriefEn: "Ask for the learner's name (real or made-up).",
    promptEn: 'Hello! I am Teacher John. Nice to meet you. What is your name?',
    promptTh: 'สวัสดีครับ ผมครูจอห์น ยินดีที่ได้รู้จัก คุณชื่ออะไรครับ?',
    retryEn: 'My name is John. What is your name?',
    retryTh: 'บอกชื่อของคุณ (จริงหรือสมมติก็ได้)',
    retryGuided: { stem: 'My name is…', emoji: '🙋', label: 'name', speak: 'My name is Maya.' },
    praiseEn: ['Nice to meet you, {name}!', 'Nice to meet you too!'],
    capture: 'name',
  }),
  beat({
    id: 't03_from',
    focusGoalIds: ['from_live'],
    npcBriefEn: 'Ask where the learner is from.',
    promptEn: 'Where are you from?',
    promptTh: 'คุณมาจากไหนครับ?',
    retryEn: "I'm from Canada. Where are you from?",
    retryTh: "ใช้ I'm from… (จริงหรือสมมติก็ได้)",
    retryGuided: { stem: "I'm from…", emoji: '🌏', label: 'Thailand', speak: "I'm from Thailand." },
    praiseEn: ['Oh, {city}! Cool!', 'Oh, cool!'],
    capture: 'city',
  }),
  beat({
    id: 't04_age',
    focusGoalIds: ['age'],
    npcBriefEn: 'Ask how old the learner is (made-up is fine).',
    promptEn: 'How old are you?',
    promptTh: 'คุณอายุเท่าไหร่ครับ?',
    retryEn: 'I am thirty-five. How old are you? Say: I am…',
    retryTh: 'บอกอายุด้วย I am + ตัวเลข',
    retryGuided: { stem: 'I am… years old.', emoji: '🎂', label: 'age', speak: 'I am twenty years old.' },
    praiseEn: ['Great!', 'Very good!'],
  }),
  beat({
    id: 't05_family',
    focusGoalIds: ['family'],
    npcBriefEn: "Ask about one person in the learner's family.",
    promptEn: 'Now, your family. Tell me about one person in your family.',
    promptTh: 'ทีนี้เรื่องครอบครัว เล่าถึงคนในครอบครัวสักหนึ่งคนครับ',
    retryEn: 'Tell me about your mother, father, sister or brother. Say: This is my…',
    retryTh: 'ใช้ This is my… แล้วบอกว่าเขาเป็นใคร',
    retryGuided: { stem: 'This is my…', emoji: '👦', label: 'brother', speak: 'This is my brother. He is a student.' },
    praiseEn: ['Wonderful!', 'How nice!'],
  }),
  beat({
    id: 't06_this_that',
    focusGoalIds: ['this_that'],
    visualLayout: 'focus_image',
    imagePath: cardPath('05-red-bag-on-bench'),
    npcBriefEn: "Picture: a red bag on a bench. John's bag is blue. He points at the red bag and asks if it is his.",
    promptEn: 'My bag is blue. Is this my bag?',
    promptTh: 'กระเป๋าของผมสีฟ้า ใบนี้ใช่กระเป๋าของผมไหมครับ?',
    retryEn: 'This bag is red. My bag is blue. Is this my bag? Say: No, it is not…',
    retryTh: 'ใบนี้สีแดง ไม่ใช่ของครู — บอกว่าไม่ใช่ แล้วชี้ใบสีฟ้า',
    retryGuided: { stem: 'No, it is not. That is…', emoji: '🔵', label: 'blue bag', speak: 'No, it is not. That is your bag.' },
    praiseEn: ["You're right. It's not my bag."],
  }),
  beat({
    id: 't07_have',
    focusGoalIds: ['have'],
    visualLayout: 'focus_image',
    imagePath: cardPath('06-red-bag-yellow-book'),
    npcBriefEn: 'Picture: an open red bag with a yellow book inside. Ask what the learner has in their bag.',
    promptEn: 'What do you have in your bag?',
    promptTh: 'ในกระเป๋าของคุณมีอะไรบ้างครับ?',
    retryEn: 'What do you have? Say: I have a…',
    retryTh: 'ใช้ I have… บอกของในกระเป๋า',
    retryGuided: { stem: 'I have…', emoji: '📒', label: 'book', speak: 'I have a book.' },
    praiseEn: ['Very good!', 'Nice!'],
  }),
  beat({
    id: 't08_plural',
    focusGoalIds: ['plural'],
    visualLayout: 'focus_image',
    imagePath: cardPath('07-three-apples'),
    npcBriefEn: 'Picture: three apples on a table. Ask how many apples there are.',
    promptEn: 'Look at the table. How many apples are there?',
    promptTh: 'ดูที่โต๊ะสิครับ มีแอปเปิลกี่ลูก?',
    retryEn: 'Count the apples. Say: There are…',
    retryTh: 'บอกจำนวน + คำนามเติม s',
    retryGuided: { stem: 'There are…', emoji: '🍎', label: 'three', speak: 'There are three apples.' },
    praiseEn: ['Yes! Three apples. Excellent!'],
  }),
  beat({
    id: 't09_wake_time',
    focusGoalIds: ['wake_time'],
    npcBriefEn: 'Ask what time they wake up.',
    promptEn: 'What time do you wake up?',
    promptTh: 'คุณตื่นนอนกี่โมงครับ?',
    retryEn: 'What time do you wake up? Say: I wake up at…',
    retryTh: 'ใช้ I wake up at + เวลา',
    retryGuided: { stem: 'I wake up at…', emoji: '🕖', label: 'seven', speak: 'I wake up at seven.' },
    praiseEn: ['Good!', 'Great!'],
  }),
  beat({
    id: 't10_her_day',
    focusGoalIds: ['her_day'],
    visualLayout: 'focus_image',
    imagePath: cardPath('09-may-wakes-at-seven'),
    npcBriefEn: "Picture: May wakes up in bed, clock shows 7:00. Ask the learner to tell May's day.",
    promptEn: "This is May's day. Tell me about her day.",
    promptTh: 'นี่คือวันของ May เล่าให้ฟังหน่อยครับ',
    retryEn: "Look. Seven o'clock, wake up. Say: She wakes up at…",
    retryTh: 'ใช้ She + กริยาเติม s เช่น She wakes up…',
    retryGuided: { stem: 'She wakes up at…', emoji: '⏰', label: '7:00', speak: 'She wakes up at seven. She works at eight.' },
    praiseEn: ['Perfect! She wakes up at seven.'],
  }),
  beat({
    id: 't11_happening_now',
    focusGoalIds: ['happening_now'],
    visualLayout: 'focus_image',
    imagePath: cardPath('10-max-eating-now'),
    npcBriefEn: 'Show Max eating a meal right now. Ask what Max is doing now.',
    promptEn: 'Look! This is Max. What is Max doing now?',
    promptTh: 'ดูสิ นี่คือ Max ตอนนี้ Max กำลังทำอะไรอยู่ครับ?',
    retryEn: 'Max is… eat… Say: He is…',
    retryTh: 'ใช้ He is + กริยา -ing',
    retryGuided: { stem: 'He is…', emoji: '🍽️', label: 'eat', speak: 'He is eating.' },
    praiseEn: ["That's right! He is eating."],
  }),
  beat({
    id: 't12_like',
    focusGoalIds: ['like'],
    npcBriefEn: 'Ask coffee or tea preference.',
    promptEn: 'I am hungry too! Do you like coffee or tea?',
    promptTh: 'ผมก็หิวเหมือนกัน! คุณชอบกาแฟหรือชาครับ?',
    emojiChoice: {
      options: [
        { emoji: '☕', label: 'coffee', speak: 'I like coffee.' },
        { emoji: '🍵', label: 'tea', speak: 'I like tea.' },
      ],
    },
    retryEn: 'Coffee or tea? Say: I like…',
    retryTh: "ใช้ I like… / I don't like…",
    retryGuided: { stem: 'I like…', emoji: '🍵', label: 'tea', speak: "I like tea. I don't like coffee." },
    praiseEn: ['Me too!', 'Good choice!'],
  }),
  beat({
    id: 't13_can',
    focusGoalIds: ['can'],
    npcBriefEn: 'Ask if they can swim (yes or no are both fine).',
    promptEn: 'Can you swim?',
    promptTh: 'คุณว่ายน้ำเป็นไหมครับ?',
    retryEn: "Can you swim? Say: Yes, I can. Or: No, I can't.",
    retryTh: "ใช้ I can… / I can't…",
    retryGuided: { stem: 'I can…', emoji: '🏊', label: 'swim', speak: 'Yes, I can. I can swim.' },
    praiseEn: ['Wow, very good!', 'Wow!'],
  }),
  beat({
    id: 't14_ask_back',
    focusGoalIds: ['ask_back'],
    npcBriefEn: "Learner's turn: ask John any simple question. John answers it.",
    promptEn: "Now it's your turn. Ask me a question!",
    promptTh: 'ถึงตาคุณแล้ว ถามผมหนึ่งคำถามครับ',
    learnerMayAsk: true,
    retryEn: 'Ask me a question. For example: Can you cook?',
    retryTh: 'ถามกลับ เช่น Can you…? / Do you like…? / Where…?',
    retryGuided: { stem: 'Can you…?', emoji: '❓', label: 'question', speak: 'Can you cook?' },
    praiseEn: ['Great question!'],
  }),
  beat({
    id: 't15_ask_price',
    focusGoalIds: ['ask_price'],
    visualLayout: 'focus_image',
    imagePath: cardPath('13-red-shirt-price-question'),
    npcBriefEn: 'Shop: red shirt, price hidden (50 baht). Learner must ask the price of the red shirt.',
    promptEn: "We're at a shop. You want this red shirt. Ask me the price.",
    promptTh: 'เราอยู่ที่ร้านค้า คุณอยากได้เสื้อสีแดงตัวนี้ ถามราคาผมหน่อยครับ',
    retryEn: 'Ask me the price. Say: How much is…?',
    retryTh: 'ถามราคาด้วย How much is…?',
    praiseEn: ['It is fifty baht. Great question!'],
  }),
  beat({
    id: 't16_directions',
    focusGoalIds: ['directions'],
    visualLayout: 'focus_image',
    imagePath: cardPath('15-straight-then-left'),
    npcBriefEn: 'Map: to reach the door go straight, then turn left. John asks which way to go.',
    promptEn: 'I need to get to that door. Which way do I go?',
    promptTh: 'ผมต้องไปที่ประตูบานนั้น ต้องไปทางไหนครับ?',
    retryEn: 'Look at the map. Say: Go straight and…',
    retryTh: 'บอกทางด้วย Go straight / Turn left',
    retryGuided: { stem: 'Go straight and…', emoji: '⬅️', label: 'left', speak: 'Go straight and turn left.' },
    praiseEn: ['Thank you! Very clear!'],
  }),
  beat({
    id: 't17_goodbye',
    focusGoalIds: ['goodbye'],
    npcBriefEn: 'Learner passed. Warm close; wait for thank you / goodbye.',
    promptEn:
      '{name}… you passed my test! I am so proud of you. The door is open. The world is waiting for you. Time to say goodbye!',
    promptTh: 'คุณผ่านบททดสอบของผมแล้ว! ประตูเปิดแล้ว โลกข้างนอกรอคุณอยู่ ถึงเวลาบอกลาแล้วครับ',
    retryEn: 'Time to say goodbye. Say: Thank you! Goodbye!',
    retryTh: 'ขอบคุณ แล้วบอกลา',
    retryGuided: { stem: 'Thank you…', emoji: '👋', label: 'goodbye', speak: 'Thank you! Goodbye!' },
    praiseEn: [],
  }),
];

export const FINAL_INTERVIEW_JOHN: InteractiveScenarioDef = {
  id: 'final_interview_john',
  mode: 'review',
  teacher: 'john',
  ttsVoiceProfile: 'teacher_john',
  titleEn: 'Final Interview',
  titleTh: 'บททดสอบสุดท้าย กับ Teacher John',
  bananaCost: 5,
  estimatedMinutes: 10,
  // Assessment: one try per question — wrong = reveal the answer, move on.
  maxAttemptsPerBeat: 1,
  softAttemptCeiling: 34,
  scenes: [
    {
      id: 'rooftop',
      titleEn: 'Rooftop',
      titleTh: 'ดาดฟ้า',
      imageAsset: ROOFTOP_BG,
      bannerAsset: ROOFTOP_BG,
    },
  ],
  goals: GOALS,
  beats: BEATS,
  openingEn: BEATS[0]!.promptEn,
  openingTh: BEATS[0]!.promptTh,
  completionEn: 'Goodbye, {name}! Go and speak English everywhere. See you out there!',
  completionTh: 'ลาก่อน! ออกไปพูดภาษาอังกฤษให้เต็มที่นะครับ แล้วเจอกันข้างนอก!',
};

/** Data-driven checkpoints authored as JSON (Adventure A2 and later courses). */
const AUTHORED_SCENARIOS = adventureA2ScenariosJson as unknown as InteractiveScenarioDef[];

const BY_ID = new Map<string, InteractiveScenarioDef>([
  [FINAL_INTERVIEW_JOHN.id, FINAL_INTERVIEW_JOHN],
  ...AUTHORED_SCENARIOS.map((scenario) => [scenario.id, scenario] as const),
]);

export function getInteractiveScenario(
  id: string,
): InteractiveScenarioDef | undefined {
  return BY_ID.get(id.trim());
}

export function listInteractiveScenarioIds(): string[] {
  return [...BY_ID.keys()];
}
